# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**/*.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**/*.md' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [7, 8, 11]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: JDK 7
      if: matrix.jdk == '7'
      run: mvn -B clean test
    - name: JDK 8
      if: matrix.jdk == '8'
      run: mvn -B package jacoco:report
    - name: JDK 11
      if: matrix.jdk == '11'
      run: mvn -B package
    - name: Upload coverage to Codecov
      if: matrix.jdk == '8'
      uses: codecov/codecov-action@v1
      with:
        file: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
    - name: Coveralls GitHub Action
      if: matrix.jdk == '8'
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/target/site/jacoco/jacoco.xml

